-- CreateEnum
CREATE TYPE "GroupType" AS ENUM (
  'THERAPEUTIC', 'WORKSHOP', 'SEMINAR', 'LECTURE',
  'LECTURE_COURSE', 'INTENSIVE', 'AUTHOR_PROGRAM', 'SUPERVISION',
  'CONFERENCE', 'CERTIFICATION', 'SPECIALIZATION', 'FOUNDATION',
  'ADVANCED', 'PROFESSIONAL', 'MODULAR', 'PARTNERSHIP',
  'INTERNATIONAL', 'PILOT', 'OTHER'
);

-- AlterTable
ALTER TABLE "Group" ADD COLUMN "type" "GroupType" NOT NULL DEFAULT 'THERAPEUTIC';

-- CreateIndex
CREATE INDEX "Group_type_idx" ON "Group"("type");
